import { writable } from 'svelte-local-storage-store';

export const papers = writable<Paper[]>('papers', []);
export const subjects = writable<Subject[]>('subjects', [
	{
		name: 'Physics',
		chapters: [
			'Physical World',
			'Units and Measurements',
			'Motion in a Straight Line',
			'Motion in a Plane',
			'Laws of Motion',
			'Work, Energy and Power',
			'System of Particles and Rotational Motion',
			'Gravitation',
			'Mechanical Properties of Solids',
			'Mechanical Properties of Fluids',
			'Thermal Properties of Matter',
			'Thermodynamics',
			'Kinetic Theory',
			'Ocillations',
			'Waves',
			'Electric Charges and Fields',
			'Electrostatic Potential and Capacitance',
			'Current Electricity',
			'Moving Charges and Magnetism',
			'Magnetism and Matter',
			'Electromagnetic Induction',
			'Alternating Current',
			'Electromagnetic Waves',
			'Ray Optics and Optical Instruments',
			'Wave Optics',
			'Dual Nature of Radiation and Matter',
			'Atoms',
			'Nuclei',
			'Semiconductor Electronics Materials, Devices and Simple Circuits'
		]
	},
	{
		name: 'Chemistry',
		chapters: [
			'Some Basic Concepts of Chemistry',
			'Structure of Atom',
			'Classification of Elements and Periodicity in Properties',
			'Chemical Bonding and Molecular Structure',
			'States of Matter',
			'Thermodynamics',
			'Equilibrium',
			'Redox Reactions',
			'Hydrogen',
			's-Block',
			'p-Block',
			'General Organic Chemistry',
			'Hydrocarbons',
			'Enviromental Chemistry',
			'The Solid State',
			'Solutions',
			'Electrochemistry',
			'Chemical Kinetics',
			'Surface Chemistry',
			'General Principles and Processes of Isolation of Elements',
			'd-Block',
			'f-Block',
			'Coordination Compounds'
		]
	},
	{
		name: 'Biology',
		chapters: [
			'The Living World',
			'Biological Classification',
			'Plant Kingdom',
			'Animal Kingdom',
			'Morphology of Flowering Plants',
			'Anatomy of Flowering Plants',
			'Structural Organisation in Animals',
			'Cell',
			'Biomolecules',
			'Cell Cycle and Cell Division',
			'Transport in Plants',
			'Mineral Nutrition',
			'Photosynthesis in Higher Plants',
			'Respiration in Plants',
			'Plant Growth and Development',
			'Digestion and Absorption',
			'Breathing and Exchange of Gases',
			'Body Fluids and Circulation',
			'Excretory Products and their Elimination',
			'Locomotion and Movement',
			'Neural Control and Coordination',
			'Chemical Coordination and Integration',
			'Reproduction in Organisms',
			'Sexual Reproduction in Flowering Plants',
			'Human Reproduction',
			'Reproductive Health',
			'Principles of Inheritance and Variation',
			'Moleculara Basis of Inheritance',
			'Evolution',
			'Human Health and Disease',
			'Strategies for Enhancement in Food Production',
			'Microbes in Human Welfare',
			'Biotechnology - Principles and Processes',
			'Biotechnology and its Applications',
			'Organisms and Populations',
			'Ecosystem',
			'Biodiversity and Conservation',
			'Enviromental Issues'
		]
	},
	{
		name: 'Maths',
		chapters: [
			'Sets',
			'Relations and Functions',
			'Trigonometric Functions',
			'Mathematical Induction',
			'Complex Numbers and Quadratic Equations',
			'Linear Inequalities',
			'Permutations and Combinations',
			'Binomial Theorem',
			'Sequences and Series',
			'Straight Lines',
			'Conic Sections',
			'3D Geometry',
			'Limits and Derivatives',
			'Mathematical Reasoning',
			'Statistics',
			'Probability',
			'Inverse Trigonometric Functions',
			'Matrices',
			'Determinants',
			'Continuity and Differentiability',
			'Application of Derivatives',
			'Integrals',
			'Application of Integrals',
			'Differential Equations',
			'Vector Algebra',
			'Linear Programming'
		]
	}
]);
